package com.bwei.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwei.greendaodem.bean.Login;
import com.bwei.greendaodem.bean.User;

import com.bwei.dao.LoginDao;
import com.bwei.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig loginDaoConfig;
    private final DaoConfig userDaoConfig;

    private final LoginDao loginDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        loginDaoConfig = daoConfigMap.get(LoginDao.class).clone();
        loginDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        loginDao = new LoginDao(loginDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Login.class, loginDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        loginDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public LoginDao getLoginDao() {
        return loginDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
